---
config:
  class:
    hideEmptyMembersBox: true
---
classDiagram
direction TB

class SolicitudInterconsulta {
  %% Identificador interno de la solicitud de interconsulta.
  %% ServiceRequest.id
  + Id : UUID

  %% Identificador de la solicitud de interconsulta generado por MINSAL luego de procesar el evento de inicio.
  + IdMinsal : UUID = NULL

  %% Identificador de la solicitud de interconsulta generado por un sistema en el establecimiento solicitante, solo si el establecimiento solicitante no es el mismo HRA.
  + IdSolicitante : UUID = NULL

  %% ServiceRequest.authoredOn
  + FechaSolicitud : DATETIME
  %% ServiceRequest.category
  + IdModalidadAtencion : UUID = NULL
  %% ServiceRequest.reasonCode
  + IdMotivoDerivacion : UUID = NULL
  %% ServiceRequest.priority
  + IdPrioridadSolicitud : UUID = NULL

  %% SLICES FOR EXTENSION
  + IdMotivoCierreInterconsulta : MotivoCierreInterconsulta.Id = NULL
  + RequiereExamen : BIT = NULL
  + EsAtencionPreferente : BIT = NULL
  + EsGES : BIT = NULL
  + EsPosibleResolverEnAPS : BIT = NULL
  + EsAlergico : BIT = NULL
  + IdReferenciaOrigen : ReferenciaOrigen.Id = NULL
  + FundamentoPriorizacion : VARCHAR = NULL
  + IdEstadoInterconsulta : EstadoInterconsulta.Id = NULL
  + IdEspecialidadMedica : EspecialidadMedica.Id = NULL
  + IdSubEspecialidadMedica : EspecialidadMedica.Id = NULL
  + IdReferenciaDestino : ReferenciaDestino.Id = NULL
  + IdPertinenciaInterconsulta : PertinenciaInterconsulta.Id = NULL

  %% SLICES FOR SUPPORTINGINFO
  %% + IdDiagnosticoInicio :
}
style SolicitudInterconsulta fill:#e4d6f5,stroke:#000000

class PertinenciaInterconsulta { <<ValueSet>> }
SolicitudInterconsulta "*" --> "0..1" PertinenciaInterconsulta
link PertinenciaInterconsulta "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSPertinenciaInterconsulta.html"
style PertinenciaInterconsulta fill:#e4d6f5,stroke:#000000

class ModalidadAtencion { <<ValueSet>> }
SolicitudInterconsulta "*" --> "0..1" ModalidadAtencion
link ModalidadAtencion "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSModalidadAtencionCodigo.html"
style ModalidadAtencion fill:#e4d6f5,stroke:#000000

class MotivoDerivacion { <<ValueSet>> }
SolicitudInterconsulta "*" --> "0..1" MotivoDerivacion
link MotivoDerivacion "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/StructureDefinition-QuestionnaireResponseIniciarLE.html"
style MotivoDerivacion fill:#e4d6f5,stroke:#000000

class PrioridadSolicitud { <<ValueSet>> }
SolicitudInterconsulta "*" --> "0..1" PrioridadSolicitud
link PrioridadSolicitud "https://hl7.org/fhir/R4/valueset-request-priority.html"
style PrioridadSolicitud fill:#e4d6f5,stroke:#000000

class ReferenciaOrigen { <<ValueSet>> }
SolicitudInterconsulta "*" --> "0..1" ReferenciaOrigen
link ReferenciaOrigen "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSorigenInterconsulta.html"
style ReferenciaOrigen fill:#e4d6f5,stroke:#000000

class ReferenciaDestino { <<ValueSet>> }
SolicitudInterconsulta "*" --> "0..1" ReferenciaDestino
link ReferenciaDestino "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSDestinoReferenciaCodigo.html"
style ReferenciaDestino fill:#e4d6f5,stroke:#000000

class MotivoCierreInterconsulta { <<ValueSet>> }
SolicitudInterconsulta "*" --> "0..1" MotivoCierreInterconsulta
link MotivoCierreInterconsulta "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSMotivoCierreInterconsulta.html"
style MotivoCierreInterconsulta fill:#e4d6f5,stroke:#000000

class EstadoInterconsulta { <<ValueSet>> }
EstadoInterconsulta "0..1" <-- "*" SolicitudInterconsulta
link EstadoInterconsulta "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSEstadoInterconsulta.html"
style EstadoInterconsulta fill:#e4d6f5,stroke:#000000

class EspecialidadMedica { <<ValueSet>> }
EspecialidadMedica "0..1" <-- "*" SolicitudInterconsulta
link EspecialidadMedica "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSEspecialidadMed.html"
style EspecialidadMedica fill:#e4d6f5,stroke:#000000

%% ---------------------------------------------------------------------------------------------


class SolicitudInterconsulta_Alergia {
  %% Identificador interno de la alergia.
  %% AllergyIntolerance.id
  + Id : UUID

  %% AllergyIntolerance.clinicalStatus
  + IdEstadoClinicoAlergia : UUID = NULL

  %% AllergyIntolerance.verificationStatus
  + IdEstadoVerificacionAlergia : UUID = NULL

  %% AllergyIntolerance.type
  + IdTipoAlergia: UUID = NULL

  %% AllergyIntolerance.criticality
  + IdCriticalidadAlergia : UUID = NULL

  %% AllergyIntolerance.code
  + IdAlergia : UUID

  %% Si es distinto de NULL debe tener la siguiente estructura:
  %% {
  %%   type: "PERIOD" | "DATETIME" | "AGE" | "STRING" | "RANGE"
  %%   value: any
  %% }
  %% Donde 'value' es del tipo indicado en 'type', correspondiente a uno de los tipos de datos de FHIR,
  %% Por ejemplo, el tipo 'DateTime' está definido en 'https://hl7.org/fhir/R4/datatypes.html#dateTime'.

  %% AllergyIntolerance.onset[FechaEstimadaAlergia.type] = FechaEstimadaAlergia.value
  + FechaEstimadaAlergia : JSON = NULL
}
style SolicitudInterconsulta_Alergia fill:#c5e1a5,stroke:#000000


SolicitudInterconsulta "1" --> "*" SolicitudInterconsulta_Alergia

class SolicitudInterconsulta_Alergia_EventoAdverso_Manifestacion {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaAlergiaEventoAdverso : UUID
  + IdManifestacionAlergia : UUID
}
style SolicitudInterconsulta_Alergia_EventoAdverso_Manifestacion fill:#c5e1a5,stroke:#000000


SolicitudInterconsulta_Alergia_EventoAdverso "1" --> "1..*" SolicitudInterconsulta_Alergia_EventoAdverso_Manifestacion


class SolicitudInterconsulta_Alergia_EventoAdverso {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaAlergia : UUID

  %% AllergyIntolerance.reaction
  + IdSeveridadAlergia : UUID
}
style SolicitudInterconsulta_Alergia_EventoAdverso fill:#c5e1a5,stroke:#000000

SolicitudInterconsulta_Alergia "1" --> "*" SolicitudInterconsulta_Alergia_EventoAdverso

class ManifestacionAlergia { <<ValueSet>> }
SolicitudInterconsulta_Alergia_EventoAdverso_Manifestacion "*" --> "1" ManifestacionAlergia
link ManifestacionAlergia "https://hl7.org/fhir/R4/valueset-clinical-findings.html"
style ManifestacionAlergia fill:#c5e1a5,stroke:#000000

class SeveridadEventoAdversoAlergia { <<ValueSet>> }
SolicitudInterconsulta_Alergia_EventoAdverso "*" --> "0..1" SeveridadEventoAdversoAlergia
link SeveridadAlergia "https://hl7.org/fhir/R4/valueset-reaction-event-severity.html"
style SeveridadEventoAdversoAlergia fill:#c5e1a5,stroke:#000000

class Alergia { <<ValueSet>> }
SolicitudInterconsulta_Alergia "*" --> "1" Alergia
link Alergia "https://hl7.org/fhir/R4/valueset-allergyintolerance-code.html"
style Alergia fill:#c5e1a5,stroke:#000000

class CriticalidadAlergia { <<ValueSet>> }
SolicitudInterconsulta_Alergia "*" --> "0..1" CriticalidadAlergia
link CriticalidadAlergia "https://hl7.org/fhir/R4/valueset-allergy-intolerance-criticality.html"
style CriticalidadAlergia fill:#c5e1a5,stroke:#000000

class TipoAlergia { <<ValueSet>> }
SolicitudInterconsulta_Alergia "*" --> "0..1" TipoAlergia
link TipoAlergia "https://hl7.org/fhir/R4/valueset-allergy-intolerance-type.html"
style TipoAlergia fill:#c5e1a5,stroke:#000000

class EstadoClinicoAlergia { <<ValueSet>> }
SolicitudInterconsulta_Alergia "*" --> "0..1" EstadoClinicoAlergia
link EstadoClinicoAlergia "https://hl7.org/fhir/R4/valueset-allergyintolerance-clinical.html"
style EstadoClinicoAlergia fill:#c5e1a5,stroke:#000000

class EstadoVerificacionAlergia { <<ValueSet>> }
SolicitudInterconsulta_Alergia "*" --> "0..1" EstadoVerificacionAlergia
link EstadoVerificacionAlergia "https://hl7.org/fhir/R4/valueset-allergyintolerance-verification.html"
style EstadoVerificacionAlergia fill:#c5e1a5,stroke:#000000

%% ---------------------------------------------------------------------------------------------

class SolicitudInterconsulta_Diagnostico {
  %% Condition.id
  + Id: UUID

  %% Condition.clinicalStatus
  + IdEstadoClinicoDiagnostico : UUID = NULL

  %% Condition.verificationStatus
  + IdEstadoVerificacionDiagnostico : UUID = NULL

  %% Condition.category
  + IdCategoriaDiagnostico : UUID

  %% Condition.severity
  + IdSeveridadDiagnostico : UUID = NULL

  %% Condition.code
  + IdDiagnostico : UUID

  %% Condition.code.text
  + DescripcionDiagnostico : VARCHAR = NULL

  %% Si es distinto de NULL debe tener la siguiente estructura:
  %% {
  %%   type: "PERIOD" | "DATETIME"
  %%   value: any
  %% }
  %% Donde 'value' es del tipo indicado en 'type', correspondiente a uno de los tipos de datos de FHIR',
  %% Por ejemplo, el tipo 'DateTime' está definido en 'https://hl7.org/fhir/R4/datatypes.html#dateTime'.

  %% Condition.onset[FechaEstimadaDiagnostico.type] = FechaEstimadaDiagnostico.value
  + FechaEstimadaDiagnostico : JSON = NULL
}
style SolicitudInterconsulta_Diagnostico fill:#c1e6ff,stroke:#000000

SolicitudInterconsulta_Diagnostico "0..1" <-- "1" SolicitudInterconsulta
link SolicitudInterconsulta_Diagnostico "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/StructureDefinition-ConditionDiagnosticoLE.html"

class EstadoClinicoDiagnostico { <<ValueSet>> }
SolicitudInterconsulta_Diagnostico "*" --> "0..1" EstadoClinicoDiagnostico
link EstadoClinicoDiagnostico "https://hl7.org/fhir/R4/valueset-condition-clinical.html"
style EstadoClinicoDiagnostico fill:#c1e6ff,stroke:#000000

class EstadoVerificacionDiagnostico { <<ValueSet>> }
SolicitudInterconsulta_Diagnostico "*" --> "0..1" EstadoVerificacionDiagnostico
link EstadoVerificacionDiagnostico "https://hl7.org/fhir/R4/valueset-condition-ver-status.html"
style EstadoVerificacionDiagnostico fill:#c1e6ff,stroke:#000000

class CategoriaDiagnostico { <<ValueSet>> }
SolicitudInterconsulta_Diagnostico "*" --> "1" CategoriaDiagnostico
link CategoriaDiagnostico "https://hl7.org/fhir/R4/valueset-condition-category.html"
style CategoriaDiagnostico fill:#c1e6ff,stroke:#000000

class SeveridadDiagnostico { <<ValueSet>> }
SolicitudInterconsulta_Diagnostico "*" --> "0..1" SeveridadDiagnostico
link SeveridadDiagnostico "https://hl7.org/fhir/R4/valueset-condition-severity.html"
style SeveridadDiagnostico fill:#c1e6ff,stroke:#000000

class Diagnostico { <<ValueSet>> }
SolicitudInterconsulta_Diagnostico "*" --> "1" Diagnostico
link Diagnostico "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSTerminologiasDiag.html"
style Diagnostico fill:#c1e6ff,stroke:#000000

%% ---------------------------------------------------------------------------------------------

SolicitudInterconsulta "0..1" --> "0..1" SolicitudInterconsulta_ObservacionIndiceComorbilidad

class SolicitudInterconsulta_ObservacionIndiceComorbilidad {
  + Id: UUID

  %% Se ignora ya que tiene un valor fijo. (final)
  %% + IdEstadoObservacion: UUID

  %% Se ignora ya que tiene un valor fijo. (ECICEP, Indice comorbilidad)
  %% + IdTipoObservacion: UUID

  %% Observation.category
  + IdCategoriaObservacion : UUID = NULL
  
  %% Si es distinto de NULL debe tener la siguiente estructura:
  %% {
  %%   type: "PERIOD" | "DATETIME" | "TIMING" | "INSTANT"
  %%   value: any
  %% }
  %% Donde 'value' es del tipo indicado en 'type', correspondiente a uno de los tipos de datos de FHIR',
  %% Por ejemplo, el tipo 'DateTime' está definido en 'https://hl7.org/fhir/R4/datatypes.html#dateTime'.

  %% Observation.effective[FechaEstimadaObservacion.type] = FechaEstimadaObservacion.value
  + FechaEstimadaObservacion : JSON = NULL

  %% Observation.value[x]
  + IdRiesgoIndiceComorbilidad : UUID

  %% Observation.note
  + Comentario : VARCHAR = NULL
}
style SolicitudInterconsulta_ObservacionIndiceComorbilidad fill:#f8c3cd,stroke:#000000


class SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidad: UUID

  %% Observation.component.code
  + IdObservacionLOINC : UUID

  %% Si es distinto de NULL debe tener la siguiente estructura:
  %% {
  %%   type: 'QUANTITY' | 'CODEABLECONCEPT' | 'STRING' | 'BOOLEAN' | 'INTEGER' | 'RANGE' | 'RATIO' | 'SAMPLEDDATA' | 'TIME' | 'DATETIME' | 'PERIOD'
  %%   value: any
  %% }
  %% Donde 'value' es del tipo indicado en 'type', correspondiente a uno de los tipos de datos de FHIR',
  %% Por ejemplo, el tipo 'DateTime' está definido en 'https://hl7.org/fhir/R4/datatypes.html#dateTime'.
  %% Observation.component.value[x]
  + ValorResultado : JSON = NULL
}

style SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado fill:#f8c3cd,stroke:#000000
SolicitudInterconsulta_ObservacionIndiceComorbilidad "1" --> "*" SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado

class SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado_Interpretacion {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidadComponenteResultado: UUID

  %% Observation.component.interpretation
  + IdInterpretacionObservacion : UUID
}

SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado_Interpretacion "*" --> "1" InterpretacionObservacion
style SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado_Interpretacion fill:#f8c3cd,stroke:#000000

SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado "1" --> "*" SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado_Interpretacion

class ObservacionLOINC { <<ValueSet>> }
SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado "*" --> "1" ObservacionLOINC
link ObservacionLOINC "https://hl7.org/fhir/R4/valueset-observation-codes.html"
style ObservacionLOINC fill:#f8c3cd,stroke:#000000

%% class ResultadoObservacionIndiceComorbilidad { <<ValueSet>> }
%% SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado "*" --> "1" ResultadoObservacionIndiceComorbilidad
%% link ResultadoObservacionIndiceComorbilidad "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSIndicecomorbilidad.html"
%% style ResultadoObservacionIndiceComorbilidad fill:#f8c3cd,stroke:#000000


class SolicitudInterconsulta_ObservacionIndiceComorbilidad_Interpretacion {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidad: UUID

  + IdInterpretacionObservacion : UUID
}
style SolicitudInterconsulta_ObservacionIndiceComorbilidad_Interpretacion fill:#f8c3cd,stroke:#000000

SolicitudInterconsulta_ObservacionIndiceComorbilidad "1" --> "*" SolicitudInterconsulta_ObservacionIndiceComorbilidad_Interpretacion

class InterpretacionObservacion { <<ValueSet>> }
SolicitudInterconsulta_ObservacionIndiceComorbilidad_Interpretacion "*" --> "1" InterpretacionObservacion
link InterpretacionObservacion "https://hl7.org/fhir/R4/valueset-observation-interpretation.html"
style InterpretacionObservacion fill:#f8c3cd,stroke:#000000


class CategoriaObservacionIndiceComorbilidad { <<ValueSet>> }
SolicitudInterconsulta_ObservacionIndiceComorbilidad "*" --> "0..1" CategoriaObservacionIndiceComorbilidad
link CategoriaObservacionIndiceComorbilidad "https://hl7.org/fhir/R4/valueset-observation-category.html"
style CategoriaObservacionIndiceComorbilidad fill:#f8c3cd,stroke:#000000

class RiesgoIndiceComorbilidad { <<ValueSet>> }
SolicitudInterconsulta_ObservacionIndiceComorbilidad "*" --> "1" RiesgoIndiceComorbilidad
link RiesgoIndiceComorbilidad "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSIndicecomorbilidad.html"
style RiesgoIndiceComorbilidad fill:#f8c3cd,stroke:#000000


%% class TipoObservacionIndiceComorbilidad { <<ValueSet>> }
%% SolicitudInterconsulta_ObservacionIndiceComorbilidad "*" --> "1" TipoObservacionIndiceComorbilidad
%% link TipoObservacionIndiceComorbilidad "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-TipoDeObservacion.html"
%% style TipoObservacionIndiceComorbilidad fill:#f8c3cd,stroke:#000000


%% ---------------------------------------------------------------------------------------------