/* https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSCodigoslenguaje.html */

USE [BD_FHIR_TIEMPOS_ESPERA_INTEROPERABLES]

DROP TABLE IF EXISTS [dbo].[ValueSet_Lenguaje];

CREATE TABLE [dbo].[ValueSet_Lenguaje] (
  Id INTEGER IDENTITY(1,1) PRIMARY KEY,
  Codigo VARCHAR(100) NOT NULL,
  Sistema VARCHAR(250) NOT NULL,
  Texto VARCHAR(250) NOT NULL,
  CONSTRAINT UQ_ValueSet_Lenguaje_Codigo_Sistema UNIQUE (Codigo, Sistema),
  CONSTRAINT CK_ValueSet_Lenguaje_SistemaUrl CHECK (Sistema LIKE 'http%')
);

INSERT INTO [dbo].[ValueSet_Lenguaje] (Codigo, Sistema, Texto) VALUES
  ('ar-SA', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Arabic (Saudi Arabia, Arabic (Saudi Arabia))'),
  ('bn-BD', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Bangla (Bangladesh, Bangla (Bangladesh))'),
  ('bn-IN', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Bangla (India, Bangla (India))'),
  ('cs-CZ', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Czech (Czech Republic, Czech (Czech Republic))'),
  ('da-DK', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Danish (Denmark, Danish (Denmark))'),
  ('de-AT', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'German (Austria, Austrian German)'),
  ('de-CH', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'German (Switzerland, Swiss German)'),
  ('de-DE', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'German (Germany, Standard German (as spoken in Germany))'),
  ('el-GR', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Greek (Greece, Modern Greek)'),
  ('en-AU', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'English (Australia, Australian English)'),
  ('en-CA', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'English (Canada, Canadian English)'),
  ('en-GB', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'English (United Kingdom, British English)'),
  ('en-IE', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'English (Ireland, Irish English)'),
  ('en-IN', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'English (India, Indian English)'),
  ('en-NZ', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'English (New Zealand, New Zealand English)'),
  ('en-US', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'English (United States, US English)'),
  ('en-ZA', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'English (South Africa, English (South Africa))'),
  ('es-AR', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Spanish (Argentina, Argentine Spanish)'),
  ('es-CL', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Spanish (Chile, Chilean Spanish)'),
  ('es-CO', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Spanish (Columbia, Colombian Spanish)'),
  ('es-ES', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Spanish (Spain, Castilian Spanish (as spoken in Central-Northern Spain))'),
  ('es-MX', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Spanish (Mexico, Mexican Spanish)'),
  ('es-US', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Spanish (United States, American Spanish)'),
  ('fi-FI', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Finnish (Finland, Finnish (Finland))'),
  ('fr-BE', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'French (Belgium, Belgian French)'),
  ('fr-CA', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'French (Canada, Canadian French)'),
  ('fr-CH', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'French (Switzerland, Swiss French)'),
  ('fr-FR', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'French (France, Standard French (especially in France))'),
  ('he-IL', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Hebrew (Israel, Hebrew (Israel))'),
  ('hi-IN', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Hindi (India, Hindi (India))'),
  ('hu-HU', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Hungarian (Hungary, Hungarian (Hungary))'),
  ('id-ID', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Indonesian (Indonesia, Indonesian (Indonesia))'),
  ('it-CH', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Italian (Switzerland, Swiss Italian)'),
  ('it-IT', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Italian (Italy, Standard Italian (as spoken in Italy))'),
  ('jp-JP', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Japanese (Japan, Japanese (Japan))'),
  ('ko-KR', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Korean (Republic of Korea, Korean (Republic of Korea))'),
  ('nl-BE', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Dutch (Belgium, Belgian Dutch)'),
  ('nl-NL', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Dutch (The Netherlands, Standard Dutch (as spoken in The Netherlands))'),
  ('no-NO', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Norwegian (Norway, Norwegian (Norway))'),
  ('pl-PL', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Polish (Poland, Polish (Poland))'),
  ('pt-BR', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Portugese (Brazil, Brazilian Portuguese)'),
  ('pt-PT', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Portugese (Portugal, European Portuguese (as written and spoken in Portugal))'),
  ('ro-RO', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Romanian (Romania, Romanian (Romania))'),
  ('ru-RU', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Russian (Russian Federation, Russian (Russian Federation))'),
  ('sk-SK', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Slovak (Slovakia, Slovak (Slovakia))'),
  ('sv-SE', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Swedish (Sweden, Swedish (Sweden))'),
  ('ta-IN', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Tamil (India, Indian Tamil)'),
  ('ta-LK', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Tamil (Sri Lanka, Sri Lankan Tamil)'),
  ('th-TH', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Thai (Thailand, Thai (Thailand))'),
  ('tr-TR', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Turkish (Turkey, Turkish (Turkey))'),
  ('zh-CN', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Chinese (China, Mainland China, simplified characters)'),
  ('zh-HK', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Chinese (Hond Kong, Hong Kong, traditional characters)'),
  ('zh-TW', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodigoslenguaje', 'Chinese (Taiwan, Taiwan, traditional characters)');