/* https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-CodPais.html */

USE [BD_FHIR_TIEMPOS_ESPERA_INTEROPERABLES]

DROP TABLE IF EXISTS [dbo].[ValueSet_Pais];

CREATE TABLE [dbo].[ValueSet_Pais] (
  Id INTEGER IDENTITY(1,1) PRIMARY KEY,
  Codigo VARCHAR(100) NOT NULL,
  Sistema VARCHAR(250) NOT NULL,
  Texto VARCHAR(250) NOT NULL,
  CONSTRAINT UQ_ValueSet_Pais_Codigo_Sistema UNIQUE (Codigo, Sistema),
  CONSTRAINT CK_ValueSet_Pais_SistemaUrl CHECK (Sistema LIKE 'http%')
);

INSERT INTO [dbo].[ValueSet_Pais] (Codigo, Sistema, Texto) VALUES
  ('004', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Afghanistan'),
  ('008', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Albania'),
  ('010', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Antarctica'),
  ('012', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Algeria'),
  ('016', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'American Samoa'),
  ('020', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Andorra'),
  ('024', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Angola'),
  ('028', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Antigua and Barbuda'),
  ('031', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Azerbaijan'),
  ('032', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Argentina'),
  ('036', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Australia'),
  ('040', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Austria'),
  ('044', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bahamas'),
  ('048', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bahrain'),
  ('050', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bangladesh'),
  ('051', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Armenia'),
  ('052', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Barbados'),
  ('056', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Belgium'),
  ('060', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bermuda'),
  ('064', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bhutan'),
  ('068', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bolivia, Plurinational State of'),
  ('070', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bosnia and Herzegovina'),
  ('072', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Botswana'),
  ('074', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bouvet Island'),
  ('076', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Brazil'),
  ('084', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Belize'),
  ('086', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'British Indian Ocean Territory'),
  ('090', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Solomon Islands'),
  ('092', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Virgin Islands, British'),
  ('096', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Brunei Darussalam'),
  ('100', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bulgaria'),
  ('104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Myanmar'),
  ('108', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Burundi'),
  ('112', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Belarus'),
  ('116', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Cambodia'),
  ('120', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Cameroon'),
  ('124', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Canada'),
  ('132', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Cabo Verde'),
  ('136', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Cayman Islands'),
  ('140', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Central African Republic'),
  ('144', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Sri Lanka'),
  ('148', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Chad'),
  ('152', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Chile'),
  ('156', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'China'),
  ('158', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Taiwan, Province of China'),
  ('162', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Christmas Island'),
  ('166', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Cocos (Keeling) Islands'),
  ('170', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Colombia'),
  ('174', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Comoros'),
  ('175', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Mayotte'),
  ('178', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Congo'),
  ('180', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Congo, the Democratic Republic of the'),
  ('184', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Cook Islands'),
  ('188', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Costa Rica'),
  ('191', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Croatia'),
  ('192', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Cuba'),
  ('196', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Cyprus'),
  ('203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Czechia'),
  ('204', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Benin'),
  ('208', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Denmark'),
  ('212', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Dominica'),
  ('214', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Dominican Republic'),
  ('218', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Ecuador'),
  ('222', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'El Salvador'),
  ('226', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Equatorial Guinea'),
  ('231', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Ethiopia'),
  ('232', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Eritrea'),
  ('233', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Estonia'),
  ('234', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Faroe Islands'),
  ('238', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Falkland Islands (Malvinas)'),
  ('239', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'South Georgia and the South Sandwich Islands'),
  ('242', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Fiji'),
  ('246', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Finland'),
  ('248', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Eland Islands'),
  ('250', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'France'),
  ('254', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'French Guiana'),
  ('258', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'French Polynesia'),
  ('260', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'French Southern Territories'),
  ('262', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Djibouti'),
  ('266', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Gabon'),
  ('268', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Georgia'),
  ('270', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Gambia'),
  ('275', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Palestine, State of'),
  ('276', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Germany'),
  ('288', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Ghana'),
  ('292', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Gibraltar'),
  ('296', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Kiribati'),
  ('300', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Greece'),
  ('304', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Greenland'),
  ('308', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Grenada'),
  ('312', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Guadeloupe'),
  ('316', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Guam'),
  ('320', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Guatemala'),
  ('324', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Guinea'),
  ('328', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Guyana'),
  ('332', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Haiti'),
  ('334', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Heard Island and McDonald Islands'),
  ('336', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Holy See'),
  ('340', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Honduras'),
  ('344', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Hong Kong'),
  ('348', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Hungary'),
  ('352', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Iceland'),
  ('356', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'India'),
  ('360', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Indonesia'),
  ('364', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Iran, Islamic Republic of'),
  ('368', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Iraq'),
  ('372', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Ireland'),
  ('376', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Israel'),
  ('380', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Italy'),
  ('384', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Ctte d"Ivoire'),
  ('388', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Jamaica'),
  ('392', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Japan'),
  ('398', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Kazakhstan'),
  ('400', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Jordan'),
  ('404', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Kenya'),
  ('408', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Korea, Democratic People"s Republic of'),
  ('410', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Korea, Republic of'),
  ('414', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Kuwait'),
  ('417', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Kyrgyzstan'),
  ('418', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Lao People"s Democratic Republic'),
  ('422', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Lebanon'),
  ('426', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Lesotho'),
  ('428', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Latvia'),
  ('430', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Liberia'),
  ('434', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Libya'),
  ('438', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Liechtenstein'),
  ('440', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Lithuania'),
  ('442', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Luxembourg'),
  ('446', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Macao'),
  ('450', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Madagascar'),
  ('454', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Malawi'),
  ('458', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Malaysia'),
  ('462', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Maldives'),
  ('466', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Mali'),
  ('470', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Malta'),
  ('474', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Martinique'),
  ('478', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Mauritania'),
  ('480', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Mauritius'),
  ('484', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Mexico'),
  ('492', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Monaco'),
  ('496', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Mongolia'),
  ('498', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Moldova, Republic of'),
  ('499', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Montenegro'),
  ('500', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Montserrat'),
  ('504', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Morocco'),
  ('508', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Mozambique'),
  ('512', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Oman'),
  ('516', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Namibia'),
  ('520', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Nauru'),
  ('524', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Nepal'),
  ('528', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Netherlands'),
  ('531', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Curagao'),
  ('533', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Aruba'),
  ('534', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Sint Maarten (Dutch part)'),
  ('535', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Bonaire, Sint Eustatius and Saba'),
  ('540', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'New Caledonia'),
  ('548', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Vanuatu'),
  ('554', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'New Zealand'),
  ('558', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Nicaragua'),
  ('562', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Niger'),
  ('566', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Nigeria'),
  ('570', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Niue'),
  ('574', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Norfolk Island'),
  ('578', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Norway'),
  ('580', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Northern Mariana Islands'),
  ('581', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'United States Minor Outlying Islands'),
  ('583', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Micronesia, Federated States of'),
  ('584', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Marshall Islands'),
  ('585', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Palau'),
  ('586', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Pakistan'),
  ('591', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Panama'),
  ('598', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Papua New Guinea'),
  ('600', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Paraguay'),
  ('604', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Peru'),
  ('608', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Philippines'),
  ('612', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Pitcairn'),
  ('616', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Poland'),
  ('620', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Portugal'),
  ('624', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Guinea-Bissau'),
  ('626', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Timor-Leste'),
  ('630', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Puerto Rico'),
  ('634', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Qatar'),
  ('638', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Riunion'),
  ('642', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Romania'),
  ('643', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Russian Federation'),
  ('646', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Rwanda'),
  ('652', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Saint Barthilemy'),
  ('654', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Saint Helena, Ascension and Tristan da Cunha'),
  ('659', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Saint Kitts and Nevis'),
  ('660', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Anguilla'),
  ('662', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Saint Lucia'),
  ('663', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Saint Martin (French part)'),
  ('666', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Saint Pierre and Miquelon'),
  ('670', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Saint Vincent and the Grenadines'),
  ('674', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'San Marino'),
  ('678', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Sao Tome and Principe'),
  ('682', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Saudi Arabia'),
  ('686', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Senegal'),
  ('688', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Serbia'),
  ('690', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Seychelles'),
  ('694', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Sierra Leone'),
  ('702', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Singapore'),
  ('703', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Slovakia'),
  ('704', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Viet Nam'),
  ('705', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Slovenia'),
  ('706', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Somalia'),
  ('710', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'South Africa'),
  ('716', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Zimbabwe'),
  ('724', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Spain'),
  ('728', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'South Sudan'),
  ('729', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Sudan'),
  ('732', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Western Sahara'),
  ('740', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Suriname'),
  ('744', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Svalbard and Jan Mayen'),
  ('748', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Swaziland'),
  ('752', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Sweden'),
  ('756', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Switzerland'),
  ('760', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Syrian Arab Republic'),
  ('762', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Tajikistan'),
  ('764', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Thailand'),
  ('768', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Togo'),
  ('772', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Tokelau'),
  ('776', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Tonga'),
  ('780', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Trinidad and Tobago'),
  ('784', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'United Arab Emirates'),
  ('788', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Tunisia'),
  ('792', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Turkey'),
  ('795', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Turkmenistan'),
  ('796', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Turks and Caicos Islands'),
  ('798', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Tuvalu'),
  ('800', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Uganda'),
  ('804', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Ukraine'),
  ('807', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Macedonia, the former Yugoslav Republic of'),
  ('818', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Egypt'),
  ('826', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'United Kingdom'),
  ('831', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Guernsey'),
  ('832', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Jersey'),
  ('833', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Isle of Man'),
  ('834', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Tanzania, United Republic of'),
  ('840', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'United States of America'),
  ('850', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Virgin Islands, U.S.'),
  ('854', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Burkina Faso'),
  ('858', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Uruguay'),
  ('860', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Uzbekistan'),
  ('862', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Venezuela, Bolivarian Republic of'),
  ('876', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Wallis and Futuna'),
  ('882', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Samoa'),
  ('887', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Yemen'),
  ('894', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CodPais', 'Zambia');