/* https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSCodigosComunaCL.html */

USE [BD_FHIR_TIEMPOS_ESPERA_INTEROPERABLES]

DROP TABLE IF EXISTS [dbo].[ValueSet_Comuna];

CREATE TABLE [dbo].[ValueSet_Comuna] (
  Id INTEGER IDENTITY(1,1) PRIMARY KEY,
  Codigo VARCHAR(100) NOT NULL,
  Sistema VARCHAR(250) NOT NULL,
  Texto VARCHAR(250) NOT NULL,
  CONSTRAINT UQ_ValueSet_Comuna_Codigo_Sistema UNIQUE (Codigo, Sistema),
  CONSTRAINT CK_ValueSet_Comuna_SistemaUrl CHECK (Sistema LIKE 'http%')
);

INSERT INTO [dbo].[ValueSet_Comuna] (Codigo, Sistema, Texto) VALUES
  ('05602', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Algarrobo'),
  ('13502', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Alhué'),
  ('08314', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Alto Biobío'),
  ('03302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Alto del Carmen'),
  ('01107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Alto Hospicio'),
  ('10202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Ancud'),
  ('04103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Andacollo'),
  ('09201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Angol'),
  ('12202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Antartica'),
  ('02101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Antofagasta'),
  ('08302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Antuco'),
  ('08202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Arauco'),
  ('15101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Arica'),
  ('11201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Aysén'),
  ('13402', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Buin'),
  ('16102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Bulnes'),
  ('05402', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cabildo'),
  ('12201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cabo de Hornos'),
  ('08303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cabrero'),
  ('02201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Calama'),
  ('10102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Calbuco'),
  ('03102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Caldera'),
  ('05502', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Calera'),
  ('13403', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Calera de Tango'),
  ('05302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Calle Larga'),
  ('15102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Camarones'),
  ('01402', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Camiña'),
  ('04202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Canela'),
  ('08203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cañete'),
  ('09102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Carahue'),
  ('05603', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cartagena'),
  ('05102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Casablanca'),
  ('10201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Castro'),
  ('05702', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Catemu'),
  ('07201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cauquenes'),
  ('13102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cerrillos'),
  ('13103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cerro Navia'),
  ('10401', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chaitén'),
  ('03201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chañaral'),
  ('07202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chanco'),
  ('06302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chépica'),
  ('08103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chiguayante'),
  ('11401', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chile Chico'),
  ('16101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chillán'),
  ('16103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chillán Viejo'),
  ('06303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chimbarongo'),
  ('09121', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cholchol'),
  ('10203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Chonchi'),
  ('11202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cisnes'),
  ('16202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cobquecura'),
  ('10103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cochamó'),
  ('11301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cochrane'),
  ('06102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Codegua'),
  ('16203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Coelemu'),
  ('11101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Coihaique'),
  ('16302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Coihueco'),
  ('06103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Coinco'),
  ('07402', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Colbún'),
  ('01403', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Colchane'),
  ('13301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Colina'),
  ('09202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Collipulli'),
  ('06104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Coltauco'),
  ('04302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Combarbalá'),
  ('08101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Concepción'),
  ('13104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Conchalí'),
  ('05103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Concón'),
  ('07102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Constitución'),
  ('08204', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Contulmo'),
  ('03101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Copiapó'),
  ('04102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Coquimbo'),
  ('08102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Coronel'),
  ('14102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Corral'),
  ('09103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Cunco'),
  ('09203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Curacautín'),
  ('13503', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Curacaví'),
  ('10204', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Curaco de Vélez'),
  ('08205', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Curanilahue'),
  ('09104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Curarrehue'),
  ('07103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Curepto'),
  ('07301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Curicó'),
  ('10205', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Dalcahue'),
  ('03202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Diego de Almagro'),
  ('06105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Doñihue'),
  ('13105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'El Bosque'),
  ('16104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'El Carmen'),
  ('13602', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'El Monte'),
  ('05604', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'El Quisco'),
  ('05605', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'El Tabo'),
  ('07104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Empedrado'),
  ('09204', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Ercilla'),
  ('13106', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Estacin Central'),
  ('08104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Florida'),
  ('09105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Freire'),
  ('03303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Freirina'),
  ('10104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Fresia'),
  ('10105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Frutillar'),
  ('10402', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Futaleufú'),
  ('14202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Futrono'),
  ('09106', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Galvarino'),
  ('15202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'General Lagos'),
  ('09107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Gorbea'),
  ('06106', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Graneros'),
  ('11203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Guaitecas'),
  ('05503', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Hijuelas'),
  ('10403', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Hualaihué'),
  ('07302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Hualañé'),
  ('08112', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Hualpén'),
  ('08105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Hualqui'),
  ('01404', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Huara'),
  ('03304', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Huasco'),
  ('13107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Huechuraba'),
  ('04201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Illapel'),
  ('13108', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Independencia'),
  ('01101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Iquique'),
  ('13603', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Isla de Maipo'),
  ('05201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Isla de Pascua'),
  ('05104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Juan Fernández'),
  ('13109', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Cisterna'),
  ('05504', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Cruz'),
  ('06202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Estrella'),
  ('13110', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Florida'),
  ('13111', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Granja'),
  ('04104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Higuera'),
  ('05401', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Ligua'),
  ('13112', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Pintana'),
  ('13113', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Reina'),
  ('04101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Serena'),
  ('14201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'La Unión'),
  ('14203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lago Ranco'),
  ('11102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lago Verde'),
  ('12102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Laguna Blanca'),
  ('08304', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Laja'),
  ('13302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lampa'),
  ('14103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lanco'),
  ('06107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Las Cabras'),
  ('13114', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Las Condes'),
  ('09108', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lautaro'),
  ('08201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lebu'),
  ('07303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Licantén'),
  ('05802', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Limache'),
  ('07401', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Linares'),
  ('06203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Litueche'),
  ('05703', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Llaillay'),
  ('10107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Llanquihue'),
  ('13115', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lo Barnechea'),
  ('13116', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lo Espejo'),
  ('13117', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lo Prado'),
  ('06304', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lolol'),
  ('09109', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Loncoche'),
  ('07403', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Longaví'),
  ('09205', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lonquimay'),
  ('08206', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Los Álamos'),
  ('05301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Los Andes'),
  ('08301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Los Ángeles'),
  ('14104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Los Lagos'),
  ('10106', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Los Muermos'),
  ('09206', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Los Sauces'),
  ('04203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Los Vilos'),
  ('08106', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lota'),
  ('09207', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Lumaco'),
  ('06108', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Machalí'),
  ('13118', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Macul'),
  ('14105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Máfil'),
  ('13119', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Maipú'),
  ('06109', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Malloa'),
  ('06204', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Marchihue'),
  ('02302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'María Elena'),
  ('13504', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'María Pinto'),
  ('14106', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Mariquina'),
  ('07105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Maule'),
  ('10108', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Maullín'),
  ('02102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Mejillones'),
  ('09110', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Melipeuco'),
  ('13501', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Melipilla'),
  ('07304', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Molina'),
  ('04303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Monte Patria'),
  ('06110', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Mostazal'),
  ('08305', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Mulchén'),
  ('08306', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Nacimiento'),
  ('06305', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Nancagua'),
  ('12401', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Natales'),
  ('06205', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Navidad'),
  ('08307', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Negrete'),
  ('16204', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Ninhue'),
  ('16303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Ñiquén'),
  ('05506', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Nogales'),
  ('09111', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Nueva Imperial'),
  ('13120', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'ÑuÑoa'),
  ('06111', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Olivar'),
  ('02202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Ollagüe'),
  ('05803', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Olmué'),
  ('10301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Osorno'),
  ('04301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Ovalle'),
  ('11302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'O"Higgins'),
  ('13604', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Padre Hurtado'),
  ('09112', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Padre las Casas'),
  ('04105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Paiguano'),
  ('14107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Paillaco'),
  ('13404', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Paine'),
  ('10404', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Palena'),
  ('06306', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Palmilla'),
  ('14108', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Panguipulli'),
  ('05704', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Panquehue'),
  ('05403', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Papudo'),
  ('06206', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Paredones'),
  ('07404', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Parral'),
  ('13121', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pedro Aguirre Cerda'),
  ('07106', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pelarco'),
  ('07203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pelluhue'),
  ('16105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pemuco'),
  ('13605', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Peñaflor'),
  ('13122', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Peñalolén'),
  ('07107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pencahue'),
  ('08107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Penco'),
  ('06307', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Peralillo'),
  ('09113', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Perquenco'),
  ('05404', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Petorca'),
  ('06112', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Peumo'),
  ('01405', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pica'),
  ('06113', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pichidegua'),
  ('06201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pichilemu'),
  ('16106', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pinto'),
  ('13202', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pirque'),
  ('09114', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pitrufquén'),
  ('06308', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Placilla'),
  ('16205', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Portezuelo'),
  ('12301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Porvenir'),
  ('01401', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pozo Almonte'),
  ('12302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Primavera'),
  ('13123', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Providencia'),
  ('05105', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Puchuncaví'),
  ('09115', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pucón'),
  ('13124', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pudahuel'),
  ('13201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Puente Alto'),
  ('10101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Puerto Montt'),
  ('10302', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Puerto Octay'),
  ('10109', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Puerto Varas'),
  ('06309', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Pumanque'),
  ('04304', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Punitaqui'),
  ('12101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Punta Arenas'),
  ('10206', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Puqueldón'),
  ('09208', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Purén'),
  ('10303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Purranque'),
  ('05705', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Putaendo'),
  ('15201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Putre'),
  ('10304', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Puyehue'),
  ('10207', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Queilén'),
  ('10208', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quellón'),
  ('10209', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quemchi'),
  ('08308', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quilaco'),
  ('13125', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quilicura'),
  ('08309', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quilleco'),
  ('16107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quillón'),
  ('05501', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quillota'),
  ('05801', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quilpué'),
  ('10210', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quinchao'),
  ('06114', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quinta de Tilcoco'),
  ('13126', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quinta Normal'),
  ('05107', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quintero'),
  ('16201', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Quirihue'),
  ('06101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Rancagua'),
  ('16206', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Ránquil'),
  ('07305', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Rauco'),
  ('13127', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Recoleta'),
  ('09209', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Renaico'),
  ('13128', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Renca'),
  ('06115', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Rengo'),
  ('06116', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Requínoa'),
  ('07405', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Retiro'),
  ('05303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Rinconada'),
  ('14204', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Río Bueno'),
  ('07108', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Río Claro'),
  ('04305', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Río Hurtado'),
  ('11402', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Río Ibáñez'),
  ('10305', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Río Negro'),
  ('12103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Río Verde'),
  ('07306', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Romeral'),
  ('09116', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Saavedra'),
  ('07307', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Sagrada Familia'),
  ('04204', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Salamanca'),
  ('05601', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Antonio'),
  ('13401', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Bernardo'),
  ('16301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Carlos'),
  ('07109', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Clemente'),
  ('05304', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Esteban'),
  ('16304', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Fabián'),
  ('05701', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Felipe'),
  ('06301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Fernando'),
  ('12104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Gregorio'),
  ('16108', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Ignacio'),
  ('07406', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Javier'),
  ('13129', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Joaquín'),
  ('13203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San José de Maipo'),
  ('10306', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Juan de la Costa'),
  ('13130', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Miguel'),
  ('16305', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Nicolás'),
  ('10307', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Pablo'),
  ('13505', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Pedro'),
  ('02203', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Pedro de Atacama'),
  ('08108', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Pedro de la Paz'),
  ('07110', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Rafael'),
  ('13131', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Ramón'),
  ('08310', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Rosendo'),
  ('06117', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'San Vicente'),
  ('08311', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Santa Bárbara'),
  ('06310', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Santa Cruz'),
  ('08109', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Santa Juana'),
  ('05706', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Santa María'),
  ('13101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Santiago Centro'),
  ('05606', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Santo Domingo'),
  ('02103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Sierra Gorda'),
  ('13601', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Talagante'),
  ('07101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Talca'),
  ('08110', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Talcahuano'),
  ('02104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Taltal'),
  ('09101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Temuco'),
  ('07308', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Teno'),
  ('09117', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Teodoro Schmidt'),
  ('03103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Tierra Amarilla'),
  ('13303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Tiltil'),
  ('12303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Timaukel'),
  ('08207', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Tirúa'),
  ('02301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Tocopilla'),
  ('09118', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Toltén'),
  ('08111', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Tomé'),
  ('12402', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Torres del Paine'),
  ('11303', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Tortel'),
  ('09210', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Traiguén'),
  ('16207', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Treguaco'),
  ('08312', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Tucapel'),
  ('14101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Valdivia'),
  ('03301', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Vallenar'),
  ('05101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Valparaíso'),
  ('07309', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Vichuqué'),
  ('09211', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Victoria'),
  ('04106', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Vicuña'),
  ('09119', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Vilcún'),
  ('07407', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Villa Alegre'),
  ('05804', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Villa Alemana'),
  ('09120', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Villarrica'),
  ('05109', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Viña del Mar'),
  ('13132', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Vitacura'),
  ('07408', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Yerbas Buenas'),
  ('08313', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Yumbel'),
  ('16109', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Yungay'),
  ('05405', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodComunasCL', 'Zapallar')