-- https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSCodigosProvinciasCL.html
INSERT INTO [dbo].[ValueSet_Provincia] (Codigo, Sistema, Texto) VALUES
  ('122', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Antártica Chilena'),
  ('021', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Antofagasta'),
  ('082', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Arauco'),
  ('151', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Arica'),
  ('112', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Aysén'),
  ('083', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Biobío'),
  ('061', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Cachapoal'),
  ('113', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Capitán Prat'),
  ('062', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Cardenal Caro'),
  ('072', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Cauquenes'),
  ('091', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Cautín'),
  ('133', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Chacabuco'),
  ('032', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Chañaral'),
  ('102', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Chiloé'),
  ('042', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Choapa'),
  ('111', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Coihaique'),
  ('063', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Colchagua'),
  ('081', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Concepción'),
  ('031', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Copiapó'),
  ('132', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Cordillera'),
  ('073', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Curicó'),
  ('161', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Diguillín'),
  ('022', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'El Loa'),
  ('041', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Elqui'),
  ('114', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'General Carrera'),
  ('033', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Huasco'),
  ('011', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Iquique'),
  ('052', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Isla de Pascua'),
  ('162', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Itata'),
  ('043', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Limarí'),
  ('074', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Linares'),
  ('101', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Llanquihue'),
  ('053', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Los Andes'),
  ('121', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Magallanes'),
  ('134', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Maipo'),
  ('092', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Malleco'),
  ('058', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Marga Marga'),
  ('135', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Melipilla'),
  ('103', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Osorno'),
  ('104', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Palena'),
  ('152', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Parinacota'),
  ('054', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Petorca'),
  ('163', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Punilla'),
  ('055', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Quillota'),
  ('142', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Ranco'),
  ('056', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'San Antonio'),
  ('057', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'San Felipe de Aconcagua'),
  ('131', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Santiago'),
  ('136', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Talagante'),
  ('071', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Talca'),
  ('014', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Tamarugal'),
  ('123', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Tierra del Fuego'),
  ('023', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Tocopilla'),
  ('124', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'última Esperanza'),
  ('141', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Valdivia'),
  ('051', 'https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSCodProvinciasCL', 'Valparaíso')