---
config:
  layout: elk
  theme: base
  class:
    hideEmptyMembersBox: true
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
---

classDiagram
direction LR


BundleIniciar --> "1" SolicitudInterconsulta
link SolicitudInterconsulta "./SolicitudInterconsulta.mmd"

BundleIniciar --> "1" AtencionInicial
link AtencionInicial "./AtencionInicial.mmd"

BundleIniciar --> "1" Paciente
link Paciente "./Paciente.mmd"

BundleIniciar --> "1" CondicionDiagnosticoInicial
link CondicionDiagnosticoInicial "./CondicionDiagnosticoInicial.mmd"


BundleIniciar --> "0..1" Observacion: Comorbilidad
BundleIniciar --> "0..1" Observacion: Discapacidad
BundleIniciar --> "0..1" Observacion: Cuidador
BundleIniciar --> "*" Observacion: Resultado examen
link Observacion "./Observacion.mmd"

BundleIniciar --> "*" AlergiaOIntolerancia
link AlergiaOIntolerancia "./AlergiaOIntolerancia.mmd"

BundleIniciar --> "1" RolProfesional
link RolProfesional "./RolProfesional.mmd"

BundleIniciar --> "1" Profesional
link Profesional "./Profesional.mmd"

BundleIniciar --> "1" EstablecimientoSalud
link EstablecimientoSalud "./EstablecimientoSalud.mmd"

BundleIniciar --> "0..1" MotivoDerivacion
link MotivoDerivacion "./MotivoDerivacion.mmd"

BundleIniciar --> "*" SolicitudExamen
link SolicitudExamen "./SolicitudExamen.mmd"
