---
config:
  layout: elk
  theme: base
  class:
    hideEmptyMembersBox: true
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
  themeCSS: |
    #ServiceRequestLE rect {
      stroke: red !important;
      fill: yellow !important;
    }
---

classDiagram
direction TB

class BundleIniciar { }

namespace ServiceRequestLE {
  class SolicitudInterconsulta {
    id: UUID
    idMinsal: UUID NULL
    
  }
}

%% --------------------------------------------------------------------------------------------------------

namespace SOLICITUD_EXAMEN {
  class SolicitudExamen {
    id : UUID

    %% Texto libre obligatorio para describir los exámenes solicitados.
    descripcion: VARCHAR

    %% Fecha en que se emite la solicitud.
    fechaSolicitud: DATETIME

    %% Fecha en la que ocurrirá el examen.
    fechaProgramada: DATETIME NULL

    %% Texto libre obligatorio para indicar el motivo de la solicitud.
    motivo: VARCHAR
    
    %% Comentario opcional. Admite formato MARKDOWN.
    comentario: VARCHAR NULL
  }

  class CodigoMotivoSolicitudExamen {
    <<ValueSet>>
  }
}

SolicitudExamen --> "*" CodigoExamen
SolicitudExamen --> "1" CodigoMotivoSolicitudExamen

link CodigoMotivoSolicitudExamen "https://hl7.org/fhir/R4/valueset-procedure-reason.html"
style CodigoMotivoSolicitudExamen fill:#FFE6A5


%% --------------------------------------------------------------------------------------------------------


class CodigoExamen {
  <<ValueSet>>
}
link CodigoExamen "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-CodigoExamen.html"
style CodigoExamen fill:#FFE6A5

%% --------------------------------------------------------------------------------------------------------

%% class ResultadoExamen {
%%   id: UUID

%% }

%% ResultadoExamen --> "*" CategoriaObservacion
%% ResultadoExamen --> "*" CodigoExamen


%% --------------------------------------------------------------------------------------------------------

namespace OBSERVACIONES {
  class Observacion {
    id: UUID
    valor: JSON
    codigo: JSON
    fechaRelevanciaClinica : JSON NULL
    interpretaciones : JSON NULL
    componentesResultado : JSON NULL
  }


  %% class ObservacionIndiceComborbilidad {
  %% }

  %% class ObservacionPacienteEsCuidador {
  %%   valor: BIT
  %% }

  %% class ObservacionPacienteTieneDiscapacidad {
  %%   valor: BIT
  %% }

  
  class CodigoRiesgoIndiceComorbilidad { <<ValueSet>> }

  class CategoriaObservacion { <<ValueSet>> }



  class Observacion_Comentario {
    texto: VARCHAR
  }


  class TipoObservacion {
    <<Enum>>
    INDICE_COMORBILIDAD
    PACIENTE_ES_CUIDADOR
    PACIENTE_TIENE_DISCAPACIDAD
    RESULTADO_EXAMEN
  }

  class EstadoObservacion { <<ValueSet>> }

  class CodigoInterpretacionObservacion { <<ValueSet>> }
}



Observacion --> "*" Observacion_Comentario


%% ObservacionPacienteEsCuidador --|> Observacion
%% ObservacionPacienteTieneDiscapacidad --|> Observacion
%% ObservacionIndiceComborbilidad --|> Observacion
%% ObservacionResultadoExamen --|> Observacion

%% ObservacionIndiceComborbilidad --> "1" CodigoRiesgoIndiceComorbilidad: .valueCodeableConcept
%% ObservacionResultadoExamen --> "1" CodigoExamen: .code




%% "Si 'Observacion.IdTipoObservacion' es
%% - 'INDICE_COMORBILIDAD' entonces 'Observacion.ValorResultado' debe ser un valor obtenido desde la tabla 'CodigoRiesgoIndiceComorbilidad'
%% - 'PACIENTE_ES_CUIDADOR' entonces 'Observacion.ValorResultado' debe ser un valor booleano/bit
%%"

Observacion --> "1" TipoObservacion
Observacion --> "1" EstadoObservacion
Observacion --> "*" CategoriaObservacion
Observacion ..> "*" CodigoInterpretacionObservacion: Si 'interpretaciones' no es nulo,\n entonces 'interpretaciones' PUEDE contener uno o más códigos\nobtenidos desde 'CodigoInterpretacionObservacion'
Observacion ..> CodigoRiesgoIndiceComorbilidad: Si el tipo de observación es 'INDICE_COMORBILIDAD'\nentonces 'valor' debe ser un\ncódigo obtenido desde esta tabla.
Observacion ..> CodigoExamen: Si el tipo de observación es 'RESULTADO_EXAMEN'\nentonces 'codigo' debe ser un\ncódigo obtenido desde esta tabla.


style SolicitudInterconsulta fill:#C4D9FF,stroke:#000000
style CodigoInterpretacionObservacion fill:#FFE6A5,stroke:#000000
style CodigoRiesgoIndiceComorbilidad fill:#FFE6A5,stroke:#000000
style CategoriaObservacion fill:#FFE6A5,stroke:#000000
style EstadoObservacion fill:#FFE6A5,stroke:#000000
style TipoObservacion fill:#FFE6A5,stroke:#000000

link CodigoInterpretacionObservacion "https://hl7.org/fhir/R4/valueset-observation-interpretation.html"
link CodigoRiesgoIndiceComorbilidad "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSIndicecomorbilidad.html"
link CategoriaObservacion "https://hl7.org/fhir/R4/valueset-observation-category.html"
link EstadoObservacion "https://hl7.org/fhir/R4/valueset-observation-status.html"
link TipoObservacion "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-TipoDeObservacion.html"


%% --------------------------------------------------------------------------------------------------------

namespace MOTIVO_DERIVACION {
  class MotivoDerivacion {
    id: UUID

    %% El motivo de derivación de la solicitud de interconsulta.
    motivo: JSON NULL
  }

  class EstadoMotivoDerivacion {
    <<ValueSet>>
  }
}
style EstadoMotivoDerivacion fill:#FFE6A5


MotivoDerivacion --> "1" EstadoMotivoDerivacion
link EstadoMotivoDerivacion "https://hl7.org/fhir/R4/valueset-questionnaire-answers-status.html"
style EstadoMotivoDerivacion fill:#FFE6A5

%% --------------------------------------------------------------------------------------------------------
namespace ESTABLECIMIENTO_SALUD {

  class EstablecimientoSalud {
    id: UUID
    codigoDEIS: VARCHAR
    nombre: VARCHAR
  }

}
%% --------------------------------------------------------------------------------------------------------

namespace PROFESIONAL {
  class Profesional {
    id: UUID
    rut: VARCHAR
    %% Codigo identificador en Registro Nacional de Prestadores Individuales, opcional.
    codigoRNPI: VARCHAR NULL

    nombre: VARCHAR
    apellidoPaterno: VARCHAR
    apellidoMaterno: VARCHAR NULL

    fechaNacimiento: DATE
  }

  class TituloProfesional {
    %% Su contenido es un array de strings
    menciones: JSON NULL

    descripcion: VARCHAR
    fechaEmision: DATETIME NULL
    fechaCaducidad: DATETIME NULL
    entidadEmisora: VARCHAR
  }

  class CodigoTipoProfesional { <<ValueSet>> }

  class EspecialidadProfesional {
    descripcion: VARCHAR
    fechaEmision: DATETIME NULL
    fechaCaducidad: DATETIME NULL
    entidadEmisora: VARCHAR NULL
  }

  class TipoEspecialidadProfesional {
    <<Enum>>
    ESPECIALIDAD
    SUBESPECIALIDAD
    ODONTOLOGICA
    FARMACOLOGICA
    BIOQUIMICA
  }


  class CodigoEspecialidadProfesional { <<ValueSet>> }

  class CodigoEspecialidadBioquimica { <<ValueSet>> }

  class CodigoEspecialidadFarmaceutica { <<ValueSet>> }

  class CodigoEspecialidadMedica { <<ValueSet>> }
  class Domicilio {
    id : UUID
    direccion: VARCHAR
    uso: 'CASA' | 'TRABAJO' | 'TEMPORAL'
  }

  class CodigoPais { <<ValueSet>> }

  class CodigoRegion { <<ValueSet>> }

  class CodigoProvincia { <<ValueSet>> }
  class CodigoComuna { <<ValueSet>> }

  class Contacto {
    id: UUID
    tipo: 'CORREO' | 'TELEFONO'
    uso: 'CASA' | 'TRABAJO' | 'TEMPORAL'
    valor: VARCHAR
    ordenPreferencia: INTEGER
  }
  class CodigoGeneroAdministrativo { <<ValueSet>> }

  class Nacionalidad { <<ValueSet>> }
  class IdentidadGenero { <<ValueSet>> }
}

Profesional --> "1..*" TituloProfesional
TituloProfesional --> "1" CodigoTipoProfesional
EspecialidadProfesional --> "1" CodigoEspecialidadProfesional
EspecialidadProfesional --> "1" TipoEspecialidadProfesional
CodigoEspecialidadProfesional <|-- CodigoEspecialidadMedica
CodigoEspecialidadProfesional <|-- CodigoEspecialidadBioquimica
CodigoEspecialidadProfesional <|-- CodigoEspecialidadFarmaceutica
Profesional --> "*" EspecialidadProfesional
CodigoEspecialidadProfesional --> "1" TipoEspecialidadProfesional
Profesional --> "0..1" Nacionalidad
Profesional --> "0..1" IdentidadGenero
Profesional --> "*" Contacto
Profesional --> "0..1" CodigoGeneroAdministrativo
Profesional --> "0..1" Domicilio
Domicilio --> "0..1" CodigoPais
Domicilio --> "0..1" CodigoRegion
Domicilio --> "0..1" CodigoProvincia
Domicilio --> "0..1" CodigoComuna

link Profesional "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/StructureDefinition-PractitionerProfesionalLE.html"
link CodigoTipoProfesional "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSTituloProfesional.html"
link CodigoEspecialidadBioquimica "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSEspecialidadBioqca.html"
link CodigoEspecialidadFarmaceutica "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSEspecialidadFarmaceutica.html"
link CodigoEspecialidadMedica "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSEspecialidadMed.html"
link CodigoRegion "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSCodigosRegionesCL.html"
link CodigoPais "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-CodPais.html"
link CodigoProvincia "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSCodigosProvinciasCL.html"
link CodigoComuna "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSCodigosComunaCL.html"
link Nacionalidad "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-CodPais.html"
link CodigoGeneroAdministrativo "https://hl7.org/fhir/R4/valueset-administrative-gender.html"
link IdentidadGenero "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSIdentidaddeGenero.html"

style CodigoRegion fill:#FFE6A5
style CodigoPais fill:#FFE6A5
style CodigoProvincia fill:#FFE6A5
style CodigoComuna fill:#FFE6A5
style CodigoTipoProfesional fill:#FFE6A5
style TipoEspecialidadProfesional fill:#FFE6A5
style CodigoEspecialidadProfesional fill:#FFE6A5,stroke-dasharray: 5 5
style CodigoEspecialidadBioquimica fill:#FFE6A5
style CodigoEspecialidadFarmaceutica fill:#FFE6A5
style CodigoEspecialidadMedica fill:#FFE6A5
style Nacionalidad fill:#FFE6A5
style CodigoGeneroAdministrativo fill:#FFE6A5
style IdentidadGenero fill:#FFE6A5

%% class CodigoUsoDomicilio { <<ValueSet>> }
%% link CodigoUsoDomicilio "http://hl7.org/fhir/R4/valueset-address-use.html"

%% class UsoContacto { <<ValueSet>> }
%% link UsoContacto "https://hl7.org/fhir/R4/valueset-contact-point-use.html"

%% class CodigoGeneroAdministrativo { <<ValueSet>> }
%% link CodigoGeneroAdministrativo "https://hl7.org/fhir/R4/valueset-administrative-gender.html"
%% style CodigoGeneroAdministrativo fill:#FFE6A5




%% Profesional --> "1" CodigoUsoDomicilio
%% Contacto "*" --> "1" UsoContacto



%% --------------------------------------------------------------------------------------------------------

namespace ROL_PROFESIONAL {  
  class RolProfesional {
    id: UUID
  }
  class CodigoRolProfesional { <<ValueSet>> }
}

RolProfesional ..> "0..1" EstablecimientoSalud
RolProfesional ..> "0..1" Profesional

link CodigoRolProfesional "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSPractitionerTipoRolLE.html"
style CodigoRolProfesional fill:#FFE6A5
RolProfesional --> "1" CodigoRolProfesional

%% class CodigoEspecialidadGeneral { <<ValueSet>> }
%% link CodigoEspecialidadGeneral "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSEspecialidadesCL.html"
%% style CodigoEspecialidadGeneral fill:#FFE6A5
%% RolProfesional --> "*" CodigoEspecialidadGeneral

%% --------------------------------------------------------------------------------------------------------

namespace ALERGIA_O_INTOLERANCIA {
  class AlergiaOIntolerancia {
    id : UUID
    fechaEstimadaDeteccion : JSON = NULL
  }

  class EventoAdverso {
  }

  class ManifestacionAlergia { <<ValueSet>> }

  class SeveridadAlergia { <<ValueSet>> }

  class CodigoAlergia { <<ValueSet>> }

  class CriticalidadAlergia { <<ValueSet>> }

  class TipoAlergia { <<ValueSet>> }

  class EstadoClinicoAlergia { <<ValueSet>> }

  class EstadoVerificacionAlergia { <<ValueSet>> }
}


EventoAdverso --> "1..*" ManifestacionAlergia
EventoAdverso --> "0..1" SeveridadAlergia

AlergiaOIntolerancia --> "*" EventoAdverso

AlergiaOIntolerancia --> "1" CodigoAlergia


AlergiaOIntolerancia --> "0..1" CriticalidadAlergia

AlergiaOIntolerancia --> "0..1" TipoAlergia

AlergiaOIntolerancia --> "0..1" EstadoClinicoAlergia

AlergiaOIntolerancia --> "0..1" EstadoVerificacionAlergia
AlergiaOIntolerancia ..> "1" Paciente

style ManifestacionAlergia fill:#FFE6A5
style SeveridadAlergia fill:#FFE6A5
style CodigoAlergia fill:#FFE6A5
style CriticalidadAlergia fill:#FFE6A5
style TipoAlergia fill:#FFE6A5
style EstadoClinicoAlergia fill:#FFE6A5
style EstadoVerificacionAlergia fill:#FFE6A5

link ManifestacionAlergia "https://hl7.org/fhir/R4/valueset-clinical-findings.html"
link SeveridadAlergia "https://hl7.org/fhir/R4/valueset-reaction-event-severity.html"
link CodigoAlergia "https://hl7.org/fhir/R4/valueset-allergyintolerance-code.html"
link CriticalidadAlergia "https://hl7.org/fhir/R4/valueset-allergy-intolerance-criticality.html"
link TipoAlergia "https://hl7.org/fhir/R4/valueset-allergy-intolerance-type.html"
link EstadoClinicoAlergia "https://hl7.org/fhir/R4/valueset-allergyintolerance-clinical.html"
link EstadoVerificacionAlergia "https://hl7.org/fhir/R4/valueset-allergyintolerance-verification.html"

%% --------------------------------------------------------------------------------------------------------

%% --------------------------------------------------------------------------------------------------------

%% class ObservacionPacienteTieneDiscapacidad { }
%% %% --------------------------------------------------------------------------------------------------------

%% class ObservacionIndiceComorbilidad { }
%% %% --------------------------------------------------------------------------------------------------------

namespace CONDICION_DIAGNOSTICO {
  class CondicionDiagnosticoInicial {
    id: UUID
    descripcion : VARCHAR NULL
    fechaEstimadaInicioDiagnostico : JSON = NULL
  }
  class EstadoClinicoDiagnostico { <<ValueSet>> }
  class EstadoVerificacionDiagnostico { <<ValueSet>> }
  class CategoriaDiagnostico { <<ValueSet>> }
  class SeveridadDiagnostico { <<ValueSet>> }
  class CodigoDiagnostico { <<ValueSet>> }
}

CondicionDiagnosticoInicial --> "0..1" EstadoClinicoDiagnostico
CondicionDiagnosticoInicial --> "0..1" EstadoVerificacionDiagnostico
CondicionDiagnosticoInicial --> "1" CategoriaDiagnostico
CondicionDiagnosticoInicial --> "0..1" SeveridadDiagnostico
CondicionDiagnosticoInicial --> "*" CodigoDiagnostico

link CondicionDiagnosticoInicial "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/StructureDefinition-ConditionDiagnosticoLE.html"
link EstadoClinicoDiagnostico "https://hl7.org/fhir/R4/valueset-condition-clinical.html"
link EstadoVerificacionDiagnostico "https://hl7.org/fhir/R4/valueset-condition-ver-status.html"
link CategoriaDiagnostico "https://hl7.org/fhir/R4/valueset-condition-category.html"
link SeveridadDiagnostico "https://hl7.org/fhir/R4/valueset-condition-severity.html"
link Diagnostico "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSTerminologiasDiag.html"

style EstadoClinicoDiagnostico fill:#FFE6A5,stroke:#000000
style EstadoVerificacionDiagnostico fill:#FFE6A5,stroke:#000000
style CategoriaDiagnostico fill:#FFE6A5,stroke:#000000
style SeveridadDiagnostico fill:#FFE6A5,stroke:#000000
style CodigoDiagnostico fill:#FFE6A5,stroke:#000000

%% --------------------------------------------------------------------------------------------------------


class Paciente { }

class AtencionInicial { }

%% SolicitudInterconsulta "1" <-- "1" BundleIniciar
%% SolicitudExamen "*" <-- "1" BundleIniciar
%% MotivoDerivacion "0..1" <-- "1" BundleIniciar
%% EstablecimientoSalud "1" <-- "1" BundleIniciar
%% Profesional "1" <-- "1" BundleIniciar
%% RolProfesional "1" <-- "1" BundleIniciar
%% AlergiaOIntolerancia "*" <-- "1" BundleIniciar
%% ResultadoExamen "*" <-- "1" BundleIniciar



BundleIniciar --> "*" Observacion
%% BundleIniciar --> "0..1" ObservacionIndiceComborbilidad
%% BundleIniciar --> "0..1" ObservacionPacienteEsCuidador
%% BundleIniciar --> "0..1" ObservacionPacienteTieneDiscapacidad
%% BundleIniciar --> "*" ObservacionResultadoExamen
%% BundleIniciar --> "*" ResultadoExamen

BundleIniciar --> "*" SolicitudExamen
BundleIniciar --> "0..1" MotivoDerivacion
BundleIniciar --> "1" EstablecimientoSalud
BundleIniciar --> "1" RolProfesional
BundleIniciar --> "1" Profesional
%% BundleIniciar --> "*" Observacion
%% BundleIniciar --> "0..1" ObservacionPacienteTieneDiscapacidad
%% BundleIniciar --> "0..1" ObservacionIndiceComorbilidad
BundleIniciar --> "1" CondicionDiagnosticoInicial
BundleIniciar --> "*" AlergiaOIntolerancia

BundleIniciar --> "1" Paciente

BundleIniciar --> "1" AtencionInicial

BundleIniciar --> "1" SolicitudInterconsulta

