---
config:
  theme: base
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
    noteBackgroundColor: "#b00b00"
---

classDiagram
direction TB

class SolicitudInterconsulta { }

class SolicitudInterconsulta_Observacion {
  + Id: UUID
  + IdSolicitudInterconsulta : UUID

  + IdTipoObservacion : INTEGER

  %% Observation.status
  + IdEstadoObservacion : UUID

  %% Observation.category ()
  + IdCategoriaObservacion : UUID = NULL
  
  %% Observation.effective[FechaEstimadaObservacion.type] = FechaEstimadaObservacion.value
  + FechaOPeriodoRelevanciaClinica : JSON = NULL

  %% Observation.value[x]
  + ValorResultado : JSON = NULL
}

note for TipoObservacion "
INDICE_COMORBILIDAD:
- codigo = 95385-1
- sistema = http://loinc.org

PACIENTE_ES_CUIDADOR:
- codigo = ECICEP
- sistema = https://interoperabilidad.minsal.cl/fhir/ig/tei/CodeSystem/CSTipoObservacionMinsal
"

class TipoObservacion {
  <<ValueSet>>
  + INDICE_COMORBILIDAD
  + PACIENTE_ES_CUIDADOR
}

class EstadoObservacion {
  <<ValueSet>> 
  + REGISTERED
  + PRELIMINARY
  + FINAL
  + ...
}

class SolicitudInterconsulta_Observacion_Categoria {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacion : UUID
  + IdCategoriaObservacion : UUID
}

class CategoriaObservacion {
  <<ValueSet>>
  + SOCIAL_HISTORY
  + VITAL_SIGNS
  + EXAM
  + ...
}

class SolicitudInterconsulta_Observacion_Comentario {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidad: UUID

  %% Observation.comment
  + Comentario : VARCHAR
}

class SolicitudInterconsulta_Observacion_ComponenteResultado {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidad: UUID

  %% Observation.component.code
  + IdObservacionLOINC : UUID

  %% Si es distinto de NULL debe tener la siguiente estructura:
  %% {
  %%   type: 'QUANTITY' | 'CODEABLECONCEPT' | 'STRING' | 'BOOLEAN' | 'INTEGER' | 'RANGE' | 'RATIO' | 'SAMPLEDDATA' | 'TIME' | 'DATETIME' | 'PERIOD'
  %%   value: any
  %% }
  %% Donde 'value' es del tipo indicado en 'type', correspondiente a uno de los tipos de datos de FHIR',
  %% Por ejemplo, el tipo 'DateTime' está definido en 'https://hl7.org/fhir/R4/datatypes.html#dateTime'.
  %% Observation.component.value[x]
  + ValorResultado : JSON = NULL
}

class SolicitudInterconsulta_Observacion_ComponenteResultado_Interpretacion {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidadComponenteResultado: UUID

  %% Observation.component.interpretation
  + IdInterpretacionObservacion : UUID
}

class ObservacionLOINC {
  <<ValueSet>>
}
krdh6335
class SolicitudInterconsulta_Observacion_Interpretacion {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidad: UUID
  + IdInterpretacionObservacion : UUID
}


class InterpretacionObservacion {
  <<ValueSet>>
  + HIGH
  + LOW
  + NEGATIVE
  + ...
}

class RiesgoIndiceComorbilidad {
  <<ValueSet>>
  + SIN_RIESGO
  + RIESGO_LEVE
  + RIESGO_MODERADO
  + RIESGO_ALTO
}

note "Si 'SolicitudInterconsulta_Observacion.IdTipoObservacion' es
- 'INDICE_COMORBILIDAD' entonces 'SolicitudInterconsulta_Observacion.ValorResultado' debe ser un valor obtenido desde la tabla 'RiesgoIndiceComorbilidad'
- 'PACIENTE_ES_CUIDADOR' entonces 'SolicitudInterconsulta_Observacion.ValorResultado' debe ser un valor booleano/bit
"

SolicitudInterconsulta "1" --> "0..1" SolicitudInterconsulta_Observacion

SolicitudInterconsulta_Observacion "*" --> "1" EstadoObservacion
SolicitudInterconsulta_Observacion "*" --> "1" TipoObservacion
SolicitudInterconsulta_Observacion "1" --> "*" SolicitudInterconsulta_Observacion_Categoria
SolicitudInterconsulta_Observacion "1" --> "*" SolicitudInterconsulta_Observacion_Comentario
SolicitudInterconsulta_Observacion "1" --> "*" SolicitudInterconsulta_Observacion_ComponenteResultado
SolicitudInterconsulta_Observacion "1" --> "*" SolicitudInterconsulta_Observacion_Interpretacion

SolicitudInterconsulta_Observacion_Interpretacion "*" --> "1" InterpretacionObservacion
SolicitudInterconsulta_Observacion_Categoria "1" --> "1" CategoriaObservacion

SolicitudInterconsulta_Observacion_ComponenteResultado "*" --> "1" ObservacionLOINC
SolicitudInterconsulta_Observacion_ComponenteResultado_Interpretacion "*" --> "1" InterpretacionObservacion
SolicitudInterconsulta_Observacion_ComponenteResultado "1" --> "*" SolicitudInterconsulta_Observacion_ComponenteResultado_Interpretacion

style SolicitudInterconsulta fill:#C4D9FF,stroke:#000000
style InterpretacionObservacion fill:#FFE6A5,stroke:#000000
style RiesgoIndiceComorbilidad fill:#FFE6A5,stroke:#000000
style CategoriaObservacion fill:#FFE6A5,stroke:#000000
style EstadoObservacion fill:#FFE6A5,stroke:#000000
style TipoObservacion fill:#FFE6A5,stroke:#000000
style ObservacionLOINC fill:#FFE6A5,stroke:#000000

link InterpretacionObservacion "https://hl7.org/fhir/R4/valueset-observation-interpretation.html"
link RiesgoIndiceComorbilidad "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSIndicecomorbilidad.html"
link ObservacionLOINC "https://hl7.org/fhir/R4/valueset-observation-codes.html"
link CategoriaObservacion "https://hl7.org/fhir/R4/valueset-observation-category.html"
link EstadoObservacion "https://hl7.org/fhir/R4/valueset-observation-status.html"
link TipoObservacion "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-TipoDeObservacion.html"