---
config:
  class:
    hideEmptyMembersBox: true
---
classDiagram
direction TB

class SolicitudInterconsulta { }
style SolicitudInterconsulta fill:#e4d6f5,stroke:#000000
link SolicitudInterconsulta "./SolicitudInterconsulta.mmd"

SolicitudInterconsulta "1" --> "0..1" SolicitudInterconsulta_ObservacionIndiceComorbilidad

class SolicitudInterconsulta_ObservacionIndiceComorbilidad {
  + Id: UUID

  %% Se ignora ya que tiene un valor fijo. (final)
  %% + IdEstadoObservacion: UUID

  %% Se ignora ya que tiene un valor fijo. (ECICEP, Indice comorbilidad)
  %% + IdTipoObservacion: UUID

  %% Observation.category
  + IdCategoriaObservacion : UUID = NULL
  
  %% Si es distinto de NULL debe tener la siguiente estructura:
  %% {
  %%   type: "PERIOD" | "DATETIME" | "TIMING" | "INSTANT"
  %%   value: any
  %% }
  %% Donde 'value' es del tipo indicado en 'type', correspondiente a uno de los tipos de datos de FHIR',
  %% Por ejemplo, el tipo 'DateTime' está definido en 'https://hl7.org/fhir/R4/datatypes.html#dateTime'.

  %% Observation.effective[FechaEstimadaObservacion.type] = FechaEstimadaObservacion.value
  + FechaEstimadaObservacion : JSON = NULL

  %% Observation.value[x]
  + IdRiesgoIndiceComorbilidad : UUID
}
style SolicitudInterconsulta_ObservacionIndiceComorbilidad fill:#f8c3cd,stroke:#000000

class SolicitudInterconsulta_ObservacionIndiceComorbilidad_Comentario {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidad: UUID

  %% Observation.comment
  + Comentario : VARCHAR
}
style SolicitudInterconsulta_ObservacionIndiceComorbilidad_Comentario fill:#f8c3cd,stroke:#000000
SolicitudInterconsulta_ObservacionIndiceComorbilidad "1" --> "*" SolicitudInterconsulta_ObservacionIndiceComorbilidad_Comentario

class SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidad: UUID

  %% Observation.component.code
  + IdObservacionLOINC : UUID

  %% Si es distinto de NULL debe tener la siguiente estructura:
  %% {
  %%   type: 'QUANTITY' | 'CODEABLECONCEPT' | 'STRING' | 'BOOLEAN' | 'INTEGER' | 'RANGE' | 'RATIO' | 'SAMPLEDDATA' | 'TIME' | 'DATETIME' | 'PERIOD'
  %%   value: any
  %% }
  %% Donde 'value' es del tipo indicado en 'type', correspondiente a uno de los tipos de datos de FHIR',
  %% Por ejemplo, el tipo 'DateTime' está definido en 'https://hl7.org/fhir/R4/datatypes.html#dateTime'.
  %% Observation.component.value[x]
  + ValorResultado : JSON = NULL
}

style SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado fill:#f8c3cd,stroke:#000000
SolicitudInterconsulta_ObservacionIndiceComorbilidad "1" --> "*" SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado

class SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado_Interpretacion {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidadComponenteResultado: UUID

  %% Observation.component.interpretation
  + IdInterpretacionObservacion : UUID
}

SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado_Interpretacion "*" --> "1" InterpretacionObservacion
style SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado_Interpretacion fill:#f8c3cd,stroke:#000000

SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado "1" --> "*" SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado_Interpretacion

class ObservacionLOINC { <<ValueSet>> }
SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado "*" --> "1" ObservacionLOINC
link ObservacionLOINC "https://hl7.org/fhir/R4/valueset-observation-codes.html"
style ObservacionLOINC fill:#f8c3cd,stroke:#000000

%% class ResultadoObservacionIndiceComorbilidad { <<ValueSet>> }
%% SolicitudInterconsulta_ObservacionIndiceComorbilidad_ComponenteResultado "*" --> "1" ResultadoObservacionIndiceComorbilidad
%% link ResultadoObservacionIndiceComorbilidad "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSIndicecomorbilidad.html"
%% style ResultadoObservacionIndiceComorbilidad fill:#f8c3cd,stroke:#000000


class SolicitudInterconsulta_ObservacionIndiceComorbilidad_Interpretacion {
  %% FK para llegar al padre.
  + IdSolicitudInterconsultaObservacionIndiceComorbilidad: UUID

  + IdInterpretacionObservacion : UUID
}
style SolicitudInterconsulta_ObservacionIndiceComorbilidad_Interpretacion fill:#f8c3cd,stroke:#000000

SolicitudInterconsulta_ObservacionIndiceComorbilidad "1" --> "*" SolicitudInterconsulta_ObservacionIndiceComorbilidad_Interpretacion

class InterpretacionObservacion { <<ValueSet>> }
SolicitudInterconsulta_ObservacionIndiceComorbilidad_Interpretacion "*" --> "1" InterpretacionObservacion
link InterpretacionObservacion "https://hl7.org/fhir/R4/valueset-observation-interpretation.html"
style InterpretacionObservacion fill:#f8c3cd,stroke:#000000


class CategoriaObservacionIndiceComorbilidad { <<ValueSet>> }
SolicitudInterconsulta_ObservacionIndiceComorbilidad "*" --> "0..1" CategoriaObservacionIndiceComorbilidad
link CategoriaObservacionIndiceComorbilidad "https://hl7.org/fhir/R4/valueset-observation-category.html"
style CategoriaObservacionIndiceComorbilidad fill:#f8c3cd,stroke:#000000

class RiesgoIndiceComorbilidad { <<ValueSet>> }
SolicitudInterconsulta_ObservacionIndiceComorbilidad "*" --> "1" RiesgoIndiceComorbilidad
link RiesgoIndiceComorbilidad "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSIndicecomorbilidad.html"
style RiesgoIndiceComorbilidad fill:#f8c3cd,stroke:#000000
