---
config:
  layout: elk
  theme: base
  class:
    hideEmptyMembersBox: true
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
---

classDiagram
direction TB

class SolicitudInterconsulta {
  id : UUID
  idMinsal : UUID NULL

  fechaSolicitud : DATETIME
  requiereExamen : BIT NULL
  esAtencionPreferente : BIT NULL
  esGES : BIT NULL
  esPosibleResolverEnAPS : BIT NULL
  esAlergico : BIT NULL
  fundamentoPriorizacion : VARCHAR NULL
  motivoNoPertinencia : VARCHAR NULL
}

class PertinenciaInterconsulta { <<ValueSet>> }
class ModalidadAtencion { <<ValueSet>> }
class MotivoDerivacion { <<ValueSet>> }
class PrioridadSolicitud { <<ValueSet>> }
class ReferenciaOrigen { <<ValueSet>> }
class ReferenciaDestino { <<ValueSet>> }


class MotivoCierreInterconsulta { <<ValueSet>> }
class EstadoInterconsulta { <<ValueSet>> }
class EspecialidadMedicaDestino { <<ValueSet>> }


SolicitudInterconsulta "*" --> "0..1" PertinenciaInterconsulta
SolicitudInterconsulta "*" --> "0..1" PrioridadSolicitud
SolicitudInterconsulta "*" --> "0..1" ReferenciaOrigen
SolicitudInterconsulta "*" --> "0..1" ModalidadAtencion
SolicitudInterconsulta "*" --> "0..1" ReferenciaDestino
SolicitudInterconsulta "*" --> "0..1" MotivoCierreInterconsulta
SolicitudInterconsulta "*" --> "0..1" EstadoInterconsulta
SolicitudInterconsulta "*" --> "0..1" EspecialidadMedicaDestino: Especialidad
SolicitudInterconsulta "*" --> "0..1" EspecialidadMedicaDestino: Subespecialidad


style SolicitudInterconsulta fill:#e4d6f5,stroke:#000000
style SolicitudInterconsulta_Alergia fill:#f8c3cd,stroke:#000000
style SolicitudInterconsulta_Diagnostico fill:#f8c3cd,stroke:#000000
style SolicitudInterconsulta_ObservacionIndiceComorbilidad fill:#f8c3cd,stroke:#000000
style PertinenciaInterconsulta fill:#e4d6f5,stroke:#000000
style ModalidadAtencion fill:#e4d6f5,stroke:#000000
style MotivoDerivacion fill:#e4d6f5,stroke:#000000
style PrioridadSolicitud fill:#e4d6f5,stroke:#000000
style ReferenciaOrigen fill:#e4d6f5,stroke:#000000
style ReferenciaDestino fill:#e4d6f5,stroke:#000000
style MotivoCierreInterconsulta fill:#e4d6f5,stroke:#000000
style EstadoInterconsulta fill:#e4d6f5,stroke:#000000
style EspecialidadMedicaDestino fill:#e4d6f5,stroke:#000000
style SolicitudInterconsulta_ObservacionPacienteCuidador fill:#f8c3cd,stroke:#000000

link SolicitudInterconsulta_ObservacionPacienteCuidador "./ObservacionPacienteCuidador.mmd"
link SolicitudInterconsulta_Diagnostico "./Diagnostico.mmd"
link SolicitudInterconsulta_ObservacionIndiceComorbilidad "./ObservacionIndiceComorbilidad.mmd"
link PertinenciaInterconsulta "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSPertinenciaInterconsulta.html"
link ModalidadAtencion "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSModalidadAtencionCodigo.html"
link MotivoDerivacion "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/StructureDefinition-QuestionnaireResponseIniciarLE.html"
link PrioridadSolicitud "https://hl7.org/fhir/R4/valueset-request-priority.html"
link ReferenciaOrigen "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSorigenInterconsulta.html"
link ReferenciaDestino "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSDestinoReferenciaCodigo.html"
link MotivoCierreInterconsulta "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSMotivoCierreInterconsulta.html"
link EstadoInterconsulta "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSEstadoInterconsulta.html"
link EspecialidadMedicaDestino "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VsEspecialidadDest.html"
