---
config:
  layout: elk
  theme: base
  class:
    hideEmptyMembersBox: true
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
---

classDiagram
direction LR



class Profesional { }
class RolProfesional { }
class EstablecimientoSalud { }





BundleIniciar --> "1" SolicitudInterconsulta
link SolicitudInterconsulta "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/SolicitudInterconsulta.mmd"

BundleIniciar --> "1" AtencionInicial
link AtencionInicial "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/AtencionInicial.mmd"

BundleIniciar --> "1" Paciente
link Paciente "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/Paciente.mmd"

BundleIniciar --> "1" CondicionDiagnostico
link CondicionDiagnostico "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/CondicionDiagnostico.mmd"

BundleIniciar --> "0..1" Observacion: Indice comorbilidad
BundleIniciar --> "0..1" Observacion: Es cuidador
BundleIniciar --> "0..1" Observacion: Tiene discapacidad
BundleIniciar --> "*" Observacion: Resultados de examenes
link Observacion "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/Observacion.mmd"

BundleIniciar --> "*" AlergiaOIntolerancia
link AlergiaOIntolerancia "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/AlergiaOIntolerancia.mmd"



BundleIniciar --> "1" RolProfesional: Iniciador
link RolProfesional "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/RolProfesional.mmd"

BundleIniciar --> "1" Profesional: Iniciador
link Profesional "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/Profesional.mmd"

BundleIniciar --> "1" EstablecimientoSalud: Iniciador
link EstablecimientoSalud "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/EstablecimientoSalud.mmd"

BundleIniciar --> "0..1" MotivoDerivacion
link MotivoDerivacion "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/MotivoDerivacion.mmd"

BundleIniciar --> "*" SolicitudExamen
link SolicitudExamen "https://github.com/chris-f23/diagramas-fhir-tei/blob/main/docs/SolicitudExamen.mmd"


%% RolProfesional ..> "1" EstablecimientoSalud
%% RolProfesional ..> "1" Profesional

%% SolicitudInterconsulta ..> "1" Paciente: Subject
%% SolicitudInterconsulta ..> "0..1" AtencionInicial: Encounter
%% SolicitudInterconsulta ..> "0..1" RolProfesional: Requester


%% AtencionInicial ..> "1" Paciente: Subject
%% AtencionInicial ..> "1" CondicionDiagnostico: Diagnostico de inicio



%% SolicitudInterconsulta ..> "0..1" CondicionDiagnostico: Diagnostico de inicio
%% SolicitudInterconsulta ..> "*" AlergiaOIntolerancia: Alergias
%% SolicitudInterconsulta ..> "0..1" Observacion: Indice de comorbilidad
%% SolicitudInterconsulta ..> "0..1" Observacion: Es cuidador
%% SolicitudInterconsulta ..> "0..1" Observacion: Tiene discapacidad
%% SolicitudInterconsulta ..> "0..1" MotivoDerivacion: Motivo de derivación
%% SolicitudInterconsulta ..> "*" SolicitudExamen: Solicitudes de examenes
%% SolicitudInterconsulta ..> "*" Observacion: Resultados de examenes