---
config:
  theme: forest
---

sequenceDiagram

autonumber

participant A as APS
participant M as MINSAL
participant H as HRA
participant BD as BD

A ->> M: Enviar 'Bundle Iniciar'
M -->> A: OK

A ->> M: Enviar 'Bundle Referenciar'
M -->> A: OK

A ->> M: Enviar 'Bundle Revisar'
M -->> A: OK

A ->> H: Enviar 'Bundle Notificar Destino'
activate H
%% H -->>A: OK, mensaje recibido y procesando en segundo plano

H ->> BD: Iniciar transacción
activate BD
H ->> BD: Crear o actualizar paciente

alt El establecimiento de salud solicitante no existe en la base de datos
  H ->> BD: Crear establecimiento de salud
end

loop Por cada prestador profesional (iniciador, referenciador, revisor)
  H ->> BD: Crear o actualizar prestador profesional
end

loop Por cada observación (indice de comorbilidad, es cuidador, tiene discapacidad)
  H ->> BD: Crear observación
end

H ->> BD: Guardar diagnostico inicial

H ->> BD: Guardar motivo de derivación

H ->> BD: Guardar atención inicial

H ->> BD: Guardar solicitud de interconsulta

H ->> BD: Guardar solicitudes de examenes

H ->> BD: Guardar resultados de examenes

H ->> BD: Guardar alergias del paciente
H ->> BD: Confirmar transacción

BD -->> H: OK
deactivate BD

H -->> A: OK, mensaje procesado correctamente
deactivate H
