USE master
GO

IF NOT EXISTS (
  SELECT name
    FROM sys.databases
    WHERE name = N'BD_ENTI_CORPORATIVA'
)
CREATE DATABASE BD_ENTI_CORPORATIVA
GO

USE BD_ENTI_CORPORATIVA
GO

-- Create table if not exists:
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PAC_Paciente')
BEGIN
  CREATE TABLE [dbo].[PAC_Paciente] (
    PAC_PAC_Numero FLOAT NOT NULL PRIMARY KEY
  )
END