---
config:
  layout: elk
  theme: base
  class:
    hideEmptyMembersBox: true
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
---

classDiagram
direction LR

class CondicionDiagnostico {
  id: UUID
  descripcion : VARCHAR NULL
  fechaEstimadaInicioDiagnostico : JSON NULL
}
class EstadoClinicoDiagnostico { <<ValueSet>> }
class EstadoVerificacionDiagnostico { <<ValueSet>> }
class CategoriaDiagnostico { <<ValueSet>> }
class SeveridadDiagnostico { <<ValueSet>> }
class CodigoDiagnostico { <<ValueSet>> }


CondicionDiagnostico --> "0..1" EstadoClinicoDiagnostico
CondicionDiagnostico --> "0..1" EstadoVerificacionDiagnostico
CondicionDiagnostico --> "1" CategoriaDiagnostico
CondicionDiagnostico --> "0..1" SeveridadDiagnostico
CondicionDiagnostico --> "*" CodigoDiagnostico

link CondicionDiagnostico "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/StructureDefinition-ConditionDiagnosticoLE.html"
link EstadoClinicoDiagnostico "https://hl7.org/fhir/R4/valueset-condition-clinical.html"
link EstadoVerificacionDiagnostico "https://hl7.org/fhir/R4/valueset-condition-ver-status.html"
link CategoriaDiagnostico "https://hl7.org/fhir/R4/valueset-condition-category.html"
link SeveridadDiagnostico "https://hl7.org/fhir/R4/valueset-condition-severity.html"
link Diagnostico "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSTerminologiasDiag.html"

style EstadoClinicoDiagnostico fill:#FFE6A5,stroke:#000000
style EstadoVerificacionDiagnostico fill:#FFE6A5,stroke:#000000
style CategoriaDiagnostico fill:#FFE6A5,stroke:#000000
style SeveridadDiagnostico fill:#FFE6A5,stroke:#000000
style CodigoDiagnostico fill:#FFE6A5,stroke:#000000

