---
config:
  layout: elk
  theme: base
  class:
    hideEmptyMembersBox: true
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
---

classDiagram
direction LR

class Observacion {
  id: UUID
  valor: JSON
  codigo: JSON
  fechaRelevanciaClinica : JSON NULL
  interpretaciones : JSON NULL
  componentesResultado : JSON NULL
}


%% class ObservacionIndiceComborbilidad {
%% }

%% class ObservacionPacienteEsCuidador {
%%   valor: BIT
%% }

%% class ObservacionPacienteTieneDiscapacidad {
%%   valor: BIT
%% }


class CodigoRiesgoIndiceComorbilidad { <<ValueSet>> }

class CategoriaObservacion { <<ValueSet>> }



class Observacion_Comentario {
  texto: VARCHAR
}


class TipoObservacion {
  <<Enum>>
  INDICE_COMORBILIDAD
  PACIENTE_ES_CUIDADOR
  PACIENTE_TIENE_DISCAPACIDAD
  RESULTADO_EXAMEN
}

class EstadoObservacion { <<ValueSet>> }

class CodigoInterpretacionObservacion { <<ValueSet>> }




Observacion --> "*" Observacion_Comentario


%% ObservacionPacienteEsCuidador --|> Observacion
%% ObservacionPacienteTieneDiscapacidad --|> Observacion
%% ObservacionIndiceComborbilidad --|> Observacion
%% ObservacionResultadoExamen --|> Observacion

%% ObservacionIndiceComborbilidad --> "1" CodigoRiesgoIndiceComorbilidad: .valueCodeableConcept
%% ObservacionResultadoExamen --> "1" CodigoExamen: .code


class CodigoExamen {
  <<ValueSet>>
}
link CodigoExamen "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-CodigoExamen.html"
style CodigoExamen fill:#FFE6A5


%% "Si 'Observacion.IdTipoObservacion' es
%% - 'INDICE_COMORBILIDAD' entonces 'Observacion.ValorResultado' debe ser un valor obtenido desde la tabla 'CodigoRiesgoIndiceComorbilidad'
%% - 'PACIENTE_ES_CUIDADOR' entonces 'Observacion.ValorResultado' debe ser un valor booleano/bit
%%"

Observacion --> "1" TipoObservacion
Observacion --> "1" EstadoObservacion
Observacion --> "*" CategoriaObservacion
Observacion ..> "*" CodigoInterpretacionObservacion: Si 'interpretaciones' no es nulo,\n entonces 'interpretaciones' PUEDE contener uno o más códigos\nobtenidos desde 'CodigoInterpretacionObservacion'
Observacion ..> "1" CodigoRiesgoIndiceComorbilidad: Si el tipo de observación es 'INDICE_COMORBILIDAD'\nentonces 'valor' debe ser un\ncódigo obtenido desde esta tabla.
Observacion ..> "1" CodigoExamen: Si el tipo de observación es 'RESULTADO_EXAMEN'\nentonces 'codigo' debe ser un\ncódigo obtenido desde esta tabla.


style SolicitudInterconsulta fill:#C4D9FF,stroke:#000000
style CodigoInterpretacionObservacion fill:#FFE6A5,stroke:#000000
style CodigoRiesgoIndiceComorbilidad fill:#FFE6A5,stroke:#000000
style CategoriaObservacion fill:#FFE6A5,stroke:#000000
style EstadoObservacion fill:#FFE6A5,stroke:#000000
style TipoObservacion fill:#FFE6A5,stroke:#000000

link CodigoInterpretacionObservacion "https://hl7.org/fhir/R4/valueset-observation-interpretation.html"
link CodigoRiesgoIndiceComorbilidad "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSIndicecomorbilidad.html"
link CategoriaObservacion "https://hl7.org/fhir/R4/valueset-observation-category.html"
link EstadoObservacion "https://hl7.org/fhir/R4/valueset-observation-status.html"
link TipoObservacion "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-TipoDeObservacion.html"

