---
config:
  layout: elk
  theme: base
  class:
    hideEmptyMembersBox: true
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
---

classDiagram
direction LR


class Prestador {
  id: UUID
  rut: VARCHAR
  %% Codigo identificador en Registro Nacional de Prestadores Individuales, opcional.
  codigoRNPI: VARCHAR NULL

  nombre: VARCHAR
  apellidoPaterno: VARCHAR
  apellidoMaterno: VARCHAR NULL

  fechaNacimiento: DATE
}



class PrestadorAdministrativo { }
class PrestadorProfesional { }

PrestadorAdministrativo --|> Prestador
PrestadorProfesional --|> Prestador


class TituloProfesional {
  %% Su contenido es un array de strings
  menciones: JSON NULL

  descripcion: VARCHAR
  fechaEmision: DATETIME NULL
  fechaCaducidad: DATETIME NULL
  entidadEmisora: VARCHAR
}

class CodigoTipoPrestador { <<ValueSet>> }

class EspecialidadProfesional {
  descripcion: VARCHAR
  fechaEmision: DATETIME NULL
  fechaCaducidad: DATETIME NULL
  entidadEmisora: VARCHAR NULL
}

class CodigoTipoEspecialidadProfesional {
  <<Enum>>
  ESPECIALIDAD
  SUBESPECIALIDAD
  ODONTOLOGICA
  FARMACOLOGICA
  BIOQUIMICA
}


class CodigoEspecialidadProfesional { <<ValueSet>> }

class CodigoEspecialidadBioquimica { <<ValueSet>> }

class CodigoEspecialidadFarmaceutica { <<ValueSet>> }

class CodigoEspecialidadMedica { <<ValueSet>> }
class Domicilio {
  id : UUID
  direccion: VARCHAR
  uso: 'CASA' | 'TRABAJO' | 'TEMPORAL'
}

class CodigoPais { <<ValueSet>> }

class CodigoRegion { <<ValueSet>> }

class CodigoProvincia { <<ValueSet>> }
class CodigoComuna { <<ValueSet>> }

class MedioContacto {
  id: UUID
  tipo: 'CORREO' | 'TELEFONO'
  uso: 'CASA' | 'TRABAJO' | 'TEMPORAL'
  valor: VARCHAR
  ordenPreferencia: INTEGER
}

class CodigoGeneroAdministrativo { <<ValueSet>> }

class CodigoNacionalidad { <<ValueSet>> }
class CodigoIdentidadGenero { <<ValueSet>> }

Domicilio --> "0..1" CodigoPais
Domicilio --> "0..1" CodigoRegion
Domicilio --> "0..1" CodigoProvincia
Domicilio --> "0..1" CodigoComuna


PrestadorProfesional --> "1..*" TituloProfesional



Prestador --> "0..1" Domicilio
Prestador --> "0..1" CodigoIdentidadGenero
Prestador --> "*" MedioContacto
Prestador --> "0..1" CodigoGeneroAdministrativo
PrestadorProfesional --> "0..1" CodigoNacionalidad

TituloProfesional --> "1" CodigoTipoPrestador
EspecialidadProfesional --> "1" CodigoEspecialidadProfesional
EspecialidadProfesional --> "1" CodigoTipoEspecialidadProfesional
CodigoEspecialidadProfesional <|-- CodigoEspecialidadMedica
CodigoEspecialidadProfesional <|-- CodigoEspecialidadBioquimica
CodigoEspecialidadProfesional <|-- CodigoEspecialidadFarmaceutica
PrestadorProfesional --> "*" EspecialidadProfesional
CodigoEspecialidadProfesional --> "1" CodigoTipoEspecialidadProfesional


link PrestadorProfesional "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/StructureDefinition-PractitionerProfesionalLE.html"
link PrestadorAdministrativo "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/StructureDefinition-PractitionerAdministrativoLE.html"

link CodigoTipoPrestador "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSTituloProfesional.html"
link CodigoEspecialidadBioquimica "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSEspecialidadBioqca.html"
link CodigoEspecialidadFarmaceutica "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSEspecialidadFarmaceutica.html"
link CodigoEspecialidadMedica "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSEspecialidadMed.html"
link CodigoRegion "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSCodigosRegionesCL.html"
link CodigoPais "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-CodPais.html"
link CodigoProvincia "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSCodigosProvinciasCL.html"
link CodigoComuna "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSCodigosComunaCL.html"
link CodigoNacionalidad "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-CodPais.html"
link CodigoGeneroAdministrativo "https://hl7.org/fhir/R4/valueset-administrative-gender.html"
link CodigoIdentidadGenero "https://hl7chile.cl/fhir/ig/clcore/1.9.2/ValueSet-VSIdentidaddeGenero.html"

style CodigoRegion fill:#FFE6A5
style CodigoPais fill:#FFE6A5
style CodigoProvincia fill:#FFE6A5
style CodigoComuna fill:#FFE6A5
style CodigoTipoPrestador fill:#FFE6A5
style CodigoTipoEspecialidadProfesional fill:#FFE6A5
style CodigoEspecialidadProfesional fill:#FFE6A5,stroke-dasharray: 5 5
style CodigoEspecialidadBioquimica fill:#FFE6A5
style CodigoEspecialidadFarmaceutica fill:#FFE6A5
style CodigoEspecialidadMedica fill:#FFE6A5
style CodigoNacionalidad fill:#FFE6A5
style CodigoGeneroAdministrativo fill:#FFE6A5
style CodigoIdentidadGenero fill:#FFE6A5

