---
config:
  layout: elk
  theme: base
  class:
    hideEmptyMembersBox: true
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
---

classDiagram
direction TB

class RolProfesional {
  id: UUID
}
class CodigoRolProfesional { <<ValueSet>> }


RolProfesional ..> "0..1" EstablecimientoSalud
RolProfesional ..> "0..1" Profesional

link CodigoRolProfesional "https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/ValueSet-VSPractitionerTipoRolLE.html"
style CodigoRolProfesional fill:#FFE6A5
RolProfesional --> "1" CodigoRolProfesional
