---
config:
  layout: elk
  theme: base
  class:
    hideEmptyMembersBox: true
  themeVariables:
    primaryBorderColor: "#000000"
    primaryColor: "#C9E6F0"
---

classDiagram
direction LR

class ValueSet {
  id : UUID
  codigo: VARCHAR
  sistema: VARCHAR
  texto: VARCHAR
}

note for ValueSet "'id' es la clave primaria"
note for ValueSet "'codigo' es único por 'sistema'"
note for ValueSet "'sistema' debe ser una URL"